import { AnimatePresence, motion } from "framer-motion";
import { X, Award, BriefcaseBusiness, GraduationCap, Sparkles, Tags } from "lucide-react";
import { useCandidate } from "../hooks/use-ranking";
import { Skeleton } from "./ui/skeleton";
import { ErrorState } from "./error-state";
import type { CandidateDetail } from "../types/api";
import type { LucideIcon } from "lucide-react";

export function CandidateDrawer({ jobId, candidateId, onClose }: { jobId?: string; candidateId?: string; onClose: () => void }) { const { data, isLoading, error, refetch } = useCandidate(jobId, candidateId); return <AnimatePresence>{candidateId ? <><motion.div className="fixed inset-0 z-40 bg-slate-900/20" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose} /><motion.aside role="dialog" aria-modal="true" aria-label="Candidate details" className="fixed inset-y-0 right-0 z-50 w-full max-w-xl overflow-y-auto border-l border-slate-200 bg-white p-6 shadow-2xl sm:p-8" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", damping: 28, stiffness: 260 }}><button onClick={onClose} className="focus-ring absolute right-5 top-5 rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="Close candidate details"><X className="h-5 w-5" /></button>{isLoading ? <DrawerSkeleton /> : error ? <ErrorState title="Unable to load candidate" error={error} onRetry={() => void refetch()} /> : data ? <DrawerContent candidate={data} /> : null}</motion.aside></> : null}</AnimatePresence>; }
function DrawerSkeleton() { return <div className="space-y-5"><Skeleton className="h-8 w-2/3" /><Skeleton className="h-20 w-full" /><Skeleton className="h-28 w-full" /></div>; }
function DrawerContent({ candidate }: { candidate: CandidateDetail }) { return <div className="pr-7"><p className="eyebrow">Candidate profile</p><h2 className="mt-2 font-[Space_Grotesk] text-2xl font-bold text-[#172554]">{candidate.name}</h2><p className="mt-1 text-sm text-slate-400">{candidate.id} · Rank #{candidate.rank}</p><div className="mt-6 grid grid-cols-2 gap-3"><Metric label="Overall score" value={candidate.score.toFixed(3)} /><Metric label="Match" value={`${candidate.matchPercentage}%`} /></div><DrawerSection icon={Tags} title="Matched skills">{candidate.matchedSkills?.length ? <div className="flex flex-wrap gap-2">{candidate.matchedSkills.map((skill) => <span key={skill} className="rounded-lg bg-indigo-50 px-2.5 py-1.5 text-xs font-bold text-indigo-700">{skill}</span>)}</div> : <Missing />}</DrawerSection><DrawerSection icon={BriefcaseBusiness} title="Experience"><p className="text-sm text-slate-600">{candidate.experience}</p></DrawerSection><DrawerSection icon={GraduationCap} title="Education"><p className="text-sm text-slate-600">{candidate.education || "Not provided by backend"}</p></DrawerSection><DrawerSection icon={Award} title="Reason codes">{candidate.reasonCodes?.length ? <ul className="space-y-2 text-sm text-slate-600">{candidate.reasonCodes.map((code) => <li key={code} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-indigo-500" />{code}</li>)}</ul> : <Missing />}</DrawerSection><DrawerSection icon={Sparkles} title="Ranking explanation"><p className="text-sm leading-6 text-slate-600">{candidate.rankingExplanation || "Not provided by backend"}</p></DrawerSection><DrawerSection icon={BriefcaseBusiness} title="Timeline">{candidate.timeline?.length ? <ol className="space-y-4 border-l border-slate-200 pl-4">{candidate.timeline.map((item, index) => <li key={`${item.title}-${index}`} className="relative"><span className="absolute -left-[21px] top-1 h-2.5 w-2.5 rounded-full bg-indigo-500" /><p className="text-sm font-bold text-slate-700">{item.title}</p><p className="text-xs text-slate-400">{[item.company, item.dateRange].filter(Boolean).join(" · ")}</p>{item.description ? <p className="mt-1 text-xs leading-5 text-slate-500">{item.description}</p> : null}</li>)}</ol> : <Missing />}</DrawerSection></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-lg font-bold text-[#172554]">{value}</p></div>; }
function DrawerSection({ icon: Icon, title, children }: { icon: LucideIcon; title: string; children: React.ReactNode }) { return <section className="mt-7"><h3 className="mb-3 flex items-center gap-2 text-sm font-bold text-slate-700"><Icon className="h-4 w-4 text-indigo-500" />{title}</h3>{children}</section>; }
const Missing = () => <p className="text-sm text-slate-400">Not provided by backend</p>;
