import { useCallback } from "react";
import { FileText, Trash2, UploadCloud } from "lucide-react";
import { useDropzone } from "react-dropzone";
import { motion } from "framer-motion";
import { cn } from "../utils/cn";

const acceptTypes = (extensions: string[]) => ({ "application/octet-stream": extensions, "text/plain": extensions, "application/pdf": extensions, "application/vnd.openxmlformats-officedocument.wordprocessingml.document": extensions, "application/x-yaml": extensions, "text/yaml": extensions });
export function UploadCard({ number, label, description, extensions, file, onFileChange, error, optional = false, tone = "purple", maxSize }: { number?: string; label: string; description: string; extensions: string[]; file?: File; onFileChange: (file?: File) => void; error?: string; optional?: boolean; tone?: "purple" | "green"; maxSize?: string }) {
  const onDrop = useCallback((accepted: File[]) => onFileChange(accepted[0]), [onFileChange]);
  const { getRootProps, getInputProps, isDragActive, open } = useDropzone({ onDrop, accept: acceptTypes(extensions), maxFiles: 1, noClick: true, noKeyboard: true });
  const isGreen = tone === "green";
  const accent = isGreen ? "text-emerald-600 bg-emerald-50 border-emerald-200 hover:border-emerald-300 hover:bg-emerald-50" : "text-indigo-600 bg-indigo-50 border-indigo-200 hover:border-indigo-300 hover:bg-indigo-50";
  return <motion.section whileHover={{ y: -2 }} className={cn("surface p-5 sm:p-6", error && "border-rose-300")}><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className={cn("grid h-7 w-7 shrink-0 place-items-center rounded-lg text-xs font-bold", isGreen ? "bg-emerald-100 text-emerald-700" : "bg-indigo-100 text-indigo-700")}>{number || "•"}</span><div><h2 className="font-bold text-[#172554]">{label} {optional ? <span className="ml-1 text-xs font-medium text-slate-400">Optional</span> : null}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div></div><span className="whitespace-nowrap rounded-md bg-slate-100 px-2 py-1 text-[11px] font-semibold text-slate-500">{extensions.join(" · ")}</span></div>{file ? <div className="mt-5 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3"><span className="rounded-lg bg-white p-2 text-emerald-600"><FileText className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-700">{file.name}</p><p className="text-xs text-slate-500">{(file.size / 1024 / 1024).toFixed(2)} MB · Ready to upload</p></div><button className="focus-ring rounded-lg p-2 text-slate-400 hover:bg-white hover:text-rose-500" aria-label={`Remove ${file.name}`} onClick={() => onFileChange(undefined)}><Trash2 className="h-4 w-4" /></button></div> : <div {...getRootProps()} className="mt-5"><input {...getInputProps()} /><div className={cn("flex min-h-40 flex-col items-center justify-center rounded-xl border border-dashed px-4 text-center transition-colors", accent, isDragActive && (isGreen ? "border-emerald-400 bg-emerald-100" : "border-indigo-400 bg-indigo-100"))}><span className={cn("mb-3 rounded-xl bg-white p-3 shadow-sm", isGreen ? "text-emerald-600" : "text-indigo-600")}><UploadCloud className="h-5 w-5" /></span><p className="text-sm font-semibold text-slate-700">Drag & drop your {extensions[0]} file here</p><button type="button" onClick={open} className={cn("focus-ring mt-1 rounded text-sm font-bold", isGreen ? "text-emerald-700" : "text-indigo-700")}>or click to browse files</button><p className="mt-3 text-xs text-slate-400">One file only {maxSize ? `• Max size: ${maxSize}` : ""}</p></div></div>}{error ? <p className="mt-2 text-xs font-medium text-rose-600">{error}</p> : null}</motion.section>;
}
