import { useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { motion } from "framer-motion";
import { BrainCircuit, LoaderCircle } from "lucide-react";
import { Button } from "../components/ui/button";
import { ProgressCard, ProcessingSteps } from "../components/progress-card";
import { ErrorState } from "../components/error-state";
import { EmptyState } from "../components/empty-state";
import { useRankingStatus } from "../hooks/use-ranking";

export function ProcessingPage() { const [params] = useSearchParams(); const jobId = params.get("jobId") || undefined; const navigate = useNavigate(); const { data, isLoading, error, refetch } = useRankingStatus(jobId); useEffect(() => { if (data?.state === "completed") navigate(`/results?jobId=${encodeURIComponent(jobId ?? "")}`, { replace: true }); }, [data?.state, jobId, navigate]); if (!jobId) return <EmptyState title="No ranking job selected" description="Start a new ranking to see live processing progress." actionLabel="Go to upload" onAction={() => navigate("/upload")} />; if (error) return <ErrorState title="Unable to get ranking status" error={error} onRetry={() => void refetch()} />; const step = data?.currentStep || "Connecting to ranking engine"; return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex min-h-[calc(100vh-10rem)] flex-col justify-center py-8 text-center"><div className="mx-auto mb-7 grid h-20 w-20 place-items-center rounded-3xl bg-indigo-50 text-indigo-600"><BrainCircuit className="h-9 w-9" /></div><p className="eyebrow">AI Processing</p><h1 className="mt-3 font-[Space_Grotesk] text-3xl font-bold text-[#172554] sm:text-4xl">Processing candidates...</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-slate-500">Keep this page open while the ranking engine processes your uploaded files.</p>{isLoading ? <div className="mt-10"><LoaderCircle className="mx-auto h-8 w-8 animate-spin text-indigo-500" /></div> : <><div className="mt-10"><ProgressCard progress={data?.progress ?? 0} step={step} /></div><ProcessingSteps currentStep={step} /></>}{data?.state === "failed" ? <div className="mx-auto mt-8 max-w-xl"><ErrorState title="Ranking failed" error={data.error} onRetry={() => void refetch()} /></div> : null}<Button variant="ghost" className="mx-auto mt-8" onClick={() => navigate("/upload")}>Cancel and return to upload</Button></motion.div>; }
